export const ENV_CONFIG = {
  VITE_BACKEND_API_BASEURL: import.meta.env.VITE_BACKEND_API_BASEURL,
  VITE_ENCRYPTION_KEY: import.meta.env.VITE_ENCRYPTION_KEY,
  VITE_ENVIRONMENT: import.meta.env.VITE_ENVIRONMENT,
};
