import { UserProfileInformationInterface } from '../../../../interface/OrgEmployeeInterface';

export const EmployeeInfoInitialState: UserProfileInformationInterface = {
  account_status: true,
  personal_info: {
    first_name: '',
    middle_name: '',
    last_name: '',
    full_name: '',
    profile_picture: '',
    gender: '',
    date_of_birth: '',
    blood_group: '',
    about: '',
    user_id: '',
  },
  employee_info: {
    status: '',
    organization_name: '',
    department: '',
    designation: '',
    reporting_manager: {
      id: '',
      first_name: '',
      last_name: '',
      middle_name: '',
      full_name: '',
      gender: '',
      profile_picture: '',
      profile_picture_bg: '',
    },
    employee_role: {
      id: '',
      role_name: '',
    },
    employee_email: '',
    employee_code: '',
    employee_type: '',
    joining_date: '',
  },
  personal_contact_info: {
    personal_email: '',
    mobile_number: '',
    country_info: '',
    emergency_contacts: [
      {
        emergency_contact_name: '',
        emergency_contact_number: '',
        emergency_contact_country_info: '',
        contact_id: '',
        id: '',
      },
    ],
  },
  family_info: {
    father_name: '',
    mother_name: '',
    marital_status: '',
    children: [
      {
        child_date_of_birth: '',
        child_name: '',
        family_info_id: '',
        id: '',
      },
    ],
  },
  current_address: {
    address: '',
    country: '',
    city: '',
    state: '',
    zip_code: '',
    country_code: '',
  },
  same_as_current_address: true,
  permanent_address: {
    address: '',
    country: '',
    city: '',
    state: '',
    zip_code: '',
    country_code: '',
  },
  social_link: [
    {
      icon: '',
      link: '',
      name: '',
      target_blank: true,
      id: '',
      user_id: '',
    },
  ],
};
